version: '3.8'

services:
  mongodb_container:
    image: mongo:latest
    restart: always
    container_name: dhwani_mongodb_container
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_DATABASE: ${MONGO_INITDB_ROOT_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27018:27017
    volumes:
      - ./mongodb_data_container:/data/db

  redis_container:
    image: redis:latest
    restart: always
    container_name: dhwani_redis_container
    env_file:
      - .env
    ports:
      - 6380:6379
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis_data:/data

volumes:
  mongodb_data_container:
  redis_data: